version: '3.8'

services:
  habit-tracker:
    build: ./
    ports:
    - "8000:8000"
    command: ./wait-for-postgres.sh db ./habit-tracker 

    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
    links:
      - db
    
  db:
    image: postgres
    restart: always
    
    volumes:
      # - ./.database/postgres/data:/var/lib/postgresql/data
      - ./schema/000001_init.up.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5432:5432"
